import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Preahvihear } from "next/font/google"; // ← هنا
import "./globals.css";
import StarBackground from "./components/three.js/starts";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const preah = Preahvihear({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-preah", // ← هنا
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${preah.variable} antialiased`}
      >
          <StarBackground/>
        {children}
       
      </body>
    </html>
  );
}
